server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2 ipv6only=on;
    server_tokens off;

    server_name instadrop.uk www.instadrop.uk;
    client_max_body_size 10m;
    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_types text/plain text/css application/json application/javascript application/xml image/svg+xml;

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;

    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 60s;
        proxy_send_timeout 60s;
    }

    ssl_certificate /etc/letsencrypt/live/instadrop.uk/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/instadrop.uk/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    listen 80;
    listen [::]:80;

    server_name instadrop.uk www.instadrop.uk;
    return 301 https://$host$request_uri;
}
