"use client";

import { useState } from "react";
import Link from "next/link";
import Image from "next/image";
import { ArrowRight, ArrowUpRight, Check, CheckCheck, ChevronDown, Clock3, FileCheck2, MapPin, PackageCheck, Route, ShieldCheck, Truck } from "lucide-react";
import { courierServices, industries } from "@/content/siteContent";
import "./home-experience.css";

const fleet = [
  { name: "Courier car", id: "courier-car", load: "25 kg", space: "Small parcels & envelopes", description: "For the little things that make a big difference. Documents, keys and small parcels, delivered directly.", kind: "car" },
  { name: "Small van", id: "small-van", load: "450 kg", space: "1 standard pallet", description: "A practical fit for everyday business. Boxes, equipment and stock with a vehicle dedicated to your delivery.", kind: "van" },
  { name: "Medium van", id: "medium-van", load: "900 kg", space: "2 standard pallets", description: "Extra room for a bigger working day. Multiple parcels, trade supplies and bulkier equipment, all together.", kind: "van" },
  { name: "Large van", id: "large-van", load: "1,200 kg", space: "3 standard pallets", description: "More space for your next move. Long loads, commercial consignments and palletised goods with direct transport.", kind: "van" },
  { name: "Luton tail-lift", id: "luton-tail-lift", load: "1,000 kg", space: "4–6 standard pallets", description: "Room for the bigger jobs. A box-body vehicle and tail-lift option for bulky equipment and pallet deliveries.", kind: "luton" },
];

function VehicleIllustration({ kind }: { kind: string }) {
  return <svg className="home-vehicle-art" viewBox="0 0 640 320" role="img" aria-label={`${kind === "car" ? "Courier car" : kind === "luton" ? "Luton tail-lift" : "Delivery van"} illustration`}>
    <ellipse cx="322" cy="277" rx="270" ry="13" fill="#0a192f" opacity=".08" />
    {kind === "car" ? <><path d="M71 218 94 171 181 154 229 104h181l70 59 81 22 23 63H65z" fill="#fff" stroke="#0a192f" strokeWidth="4" /><path d="m203 156 40-39h65v45h-112zm119-39h80l48 45H322z" fill="#0a192f" /><path d="M85 199h471v25H74z" fill="#c6ff00" /></> : <><path d={kind === "luton" ? "M64 75h328v160H64z" : "M64 118q0-29 29-29h284l80 84 102 23 18 51H64z"} fill="#fff" stroke="#0a192f" strokeWidth="4" />{kind === "luton" && <path d="M392 142h85l55 51 42 17v37H392z" fill="#fff" stroke="#0a192f" strokeWidth="4" />}<path d={kind === "luton" ? "M410 154h59l39 40h-98z" : "M350 108h19l63 65h-82z"} fill="#0a192f" /><path d="M68 202h476v24H68z" fill="#c6ff00" /><path d="M330 111v129" stroke="#cbd5e1" strokeWidth="2" /><path d="M347 188h18" stroke="#0a192f" strokeWidth="4" strokeLinecap="round" /></>}
    <rect x="60" y="238" width="521" height="15" rx="5" fill="#0a192f" />
    {[160, 480].map(cx => <g key={cx}><circle cx={cx} cy="250" r="37" fill="#0a192f" /><circle cx={cx} cy="250" r="23" fill="#dce3e8" /><circle cx={cx} cy="250" r="10" fill="#8392a4" /></g>)}
    <text x={kind === "car" ? "260" : "125"} y={kind === "car" ? "194" : "163"} fontFamily="Arial, sans-serif" fontSize="28" fontWeight="800" fill="#0a192f">Insta<tspan fill="#529600">Drop</tspan></text>
    <path d="M88 136H40m42 21H23m55 21H47" stroke="#0a192f" strokeWidth="4" strokeLinecap="round" opacity=".25" />
    <rect x="553" y="207" width="14" height="10" rx="3" fill="#e5edff" />
  </svg>;
}

export default function HomeExperience() {
  const [serviceIndex, setServiceIndex] = useState(0);
  const [vehicleIndex, setVehicleIndex] = useState(1);
  const selectedService = courierServices[serviceIndex];
  const vehicle = fleet[vehicleIndex];
  return <div className="home-experience">
    <div className="home-promise-strip"><div className="home-wrap">{[{ icon: Route, title: "Direct, door to door", text: "A dedicated journey for your goods" }, { icon: Clock3, title: "Around your schedule", text: "Urgent or planned collections" }, { icon: FileCheck2, title: "Delivery, documented", text: "Tracking and proof of delivery" }].map(({icon: Icon, title, text}) => <div key={title} className="home-promise"><Icon size={25} /><div><strong>{title}</strong><span>{text}</span></div></div>)}</div></div>

    <section id="services" className="home-section home-wrap">
      <div className="home-heading"><div><span className="home-kicker">01 / MADE TO MOVE</span><h2>Big deadlines.<br />Small details.<br /><span>We get both.</span></h2></div><p>From a single envelope to a full van load, find the right delivery service for whatever your day brings.</p></div>
      <div className="home-service-layout"><div className="home-service-visual"><Image src="/blog/packing.jpg" alt="A parcel carefully packed and prepared for collection" fill sizes="(max-width: 900px) 100vw, 50vw" /><div className="home-image-note"><span className="home-status-dot" /><span>YOUR GOODS. OUR PRIORITY.</span><ArrowUpRight size={21} /></div><div className="home-service-caption"><span>Care at every step.</span><p>From the first collection<br />to the final handover.</p></div></div><div className="home-service-list">{courierServices.map((service, i) => <div className={`home-service-row ${serviceIndex === i ? "is-open" : ""}`} key={service.slug}><h3><button type="button" aria-expanded={serviceIndex === i} aria-controls={`home-service-${i}`} onClick={() => setServiceIndex(i)}><span className="home-index">0{i + 1}</span><span>{service.title}</span><ChevronDown size={19} /></button></h3><div id={`home-service-${i}`} hidden={serviceIndex !== i}><p>{service.description}</p><Link href={`/${service.slug}`} className="home-text-link">Explore this service <ArrowUpRight size={17} /></Link></div></div>)}<Link className="home-text-link home-all-services" href="/services">See all courier services <ArrowRight size={18} /></Link></div></div>
      <p className="sr-only" aria-live="polite">Selected service: {selectedService.title}</p>
    </section>

    <section className="home-process"><div className="home-wrap"><div className="home-heading"><div><span className="home-kicker">02 / SIMPLE FROM THE START</span><h2>You have enough to do.<br /><span>Leave the journey to us.</span></h2></div><Link href="/instant-quote" className="home-button home-button-lime">Let’s get moving <ArrowUpRight size={18} /></Link></div><div className="home-steps">{[{title:"Tell us what’s moving",text:"Share your postcodes, load details and preferred collection time. We’ll work out the right option.",icon:MapPin},{title:"Confirm your delivery",text:"Dispatch confirms the plan and price. Review your quote and pay securely to complete your booking.",icon:ShieldCheck},{title:"We’ll take it from here",text:"Your dedicated vehicle collects and delivers. Follow the recorded updates and access POD after handover.",icon:PackageCheck}].map(({title,text,icon:Icon},i)=><div className="home-step" key={title}><div className="home-step-top"><span>0{i+1}</span><Icon size={25} /></div><h3>{title}</h3><p>{text}</p></div>)}</div></div></section>

    <section className="home-section home-wrap home-industries"><div className="home-industry-intro"><span className="home-kicker">03 / PART OF YOUR WORKING DAY</span><h2>Different industries.<br /><span>The same commitment.</span></h2><p>Some deliveries keep a project moving. Others help a business keep its promise. We understand what’s riding on yours.</p><Link href="/industries" className="home-text-link">Find your industry <ArrowUpRight size={18} /></Link><div className="home-industry-photo"><Image src="/blog/warehouse.jpg" alt="Warehouse goods organised for business dispatch" fill sizes="(max-width: 900px) 100vw, 40vw" /><span>Keeping business moving.</span></div></div><div className="home-industry-list">{industries.map(industry=>{const Icon=industry.icon;return <Link href={`/industries/${industry.slug}`} key={industry.slug}><Icon className="home-industry-icon" size={24}/><div><h3>{industry.title}</h3><p>{industry.consignments}</p></div><ArrowUpRight size={19}/></Link>;})}</div></section>

    <section id="fleet" className="home-fleet"><div className="home-wrap"><div className="home-heading"><div><span className="home-kicker">04 / THE RIGHT FIT</span><h2>Small parcel?<br /><span>Meet your next vehicle.</span></h2></div><p>Choose a vehicle to explore the options. We’ll confirm the right fit for your goods when you book.</p></div><div className="home-fleet-tabs" role="tablist" aria-label="Explore vehicle types">{fleet.map((item,i)=><button type="button" key={item.id} role="tab" id={`fleet-tab-${i}`} aria-selected={vehicleIndex===i} tabIndex={vehicleIndex===i ? 0 : -1} aria-controls="home-fleet-panel" onKeyDown={event => {
        const next = event.key === "ArrowRight" ? (i + 1) % fleet.length : event.key === "ArrowLeft" ? (i + fleet.length - 1) % fleet.length : event.key === "Home" ? 0 : event.key === "End" ? fleet.length - 1 : null;
        if (next !== null) { event.preventDefault(); setVehicleIndex(next); document.getElementById(`fleet-tab-${next}`)?.focus(); }
      }} onClick={()=>setVehicleIndex(i)}>{item.name}</button>)}</div><div className="home-fleet-stage" id="home-fleet-panel" role="tabpanel" aria-labelledby={`fleet-tab-${vehicleIndex}`}><div className="home-fleet-art"><span className="home-fleet-watermark" aria-hidden="true">LET’S GO.</span><VehicleIllustration kind={vehicle.kind}/><span className="home-illustration-note">Vehicle illustration · Actual vehicle may vary</span></div><div className="home-fleet-details"><span className="home-kicker">DEDICATED TO YOUR DELIVERY</span><h3>{vehicle.name}</h3><p>{vehicle.description}</p><div className="home-fleet-specs"><div><span>Payload up to</span><strong>{vehicle.load}</strong></div><div><span>Load guide</span><strong>{vehicle.space}</strong></div></div><Link href={`/vehicle-fleet#${vehicle.id}`} className="home-text-link">View vehicle details <ArrowUpRight size={18}/></Link></div></div></div></section>

    <section className="home-section home-wrap home-tracking"><div className="home-tracking-visual" aria-hidden="true"><div className="home-tracking-top"><span className="home-status-dot"/> EVERY STEP ACCOUNTED FOR <Route size={22}/></div><div className="home-route-line"><div><span><PackageCheck size={22}/></span><strong>Collected</strong><small>Ready for the journey</small></div><div><span><Truck size={22}/></span><strong>On the road</strong><small>Moving towards your destination</small></div><div><span><CheckCheck size={22}/></span><strong>Delivered</strong><small>A clear handover record</small></div></div><div className="home-pod-slip"><FileCheck2 size={26}/><div><strong>Proof of delivery</strong><span>Recipient · Signature · Delivery photo</span></div><Check size={19}/></div></div><div><span className="home-kicker">05 / A LITTLE MORE PEACE OF MIND</span><h2>The journey matters.<br /><span>So does knowing.</span></h2><p>Stay connected to your delivery. View the latest status recorded by dispatch and access recipient details, signatures or photos when proof of delivery is available.</p><Link href="/track-delivery" className="home-button">Track your delivery <ArrowUpRight size={18}/></Link><div className="home-tracking-footnote"><FileCheck2 size={16}/><span>Keep your booking reference handy.</span></div></div></section>

    <section className="home-closing"><div className="home-wrap"><div><span className="home-kicker">ONE LESS THING ON YOUR TO-DO LIST</span><h2>Consider it<br /><span>on its way.</span></h2></div><div><p>Tell us where, when and what.<br />We’ll help you take care of the rest.</p><Link href="/instant-quote" className="home-button home-button-lime">Get your speedy quote <ArrowUpRight size={20}/></Link><Link href="/contact" className="home-closing-contact">Have a question? Talk to dispatch <ArrowRight size={16}/></Link></div></div></section>
  </div>;
}
